version: 2

updates:
# keep up to date the github actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly

# keep up to date the base docker image
- package-ecosystem: docker
  directories:
  - containers/base
  - containers/docker
  - containers/go
  - containers/kubernetes
  - containers/node
  - containers/sysdig
  schedule:
    interval: daily

# keep up to date devcontainers
- package-ecosystem: devcontainers
  directory: "/"
  schedule:
    interval: monthly
