version: 2
updates:
# keep up to date the github actions
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: monthly

# keep up to date the base docker image
- package-ecosystem: docker
  directory: /
  schedule:
    interval: daily
