include:
- project: mia-platform/pipeline-templates
  file: Application.gitlab-ci.yml
  ref: HEAD

workflow:
  rules:
  - if: $CI_MERGE_REQUEST_IID
  - if: $CI_COMMIT_TAG
  - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

variables:
  NODE_IMAGE_TAG: "20"
  IMAGE_NAME: mia_template_image_name_placeholder

build:
  extends: .npm-build
  stage: build

lint:
  extends: .npm-lint
  stage: sast

test:
  extends: .npm-test
  stage: test

docker:build:
  extends: .docker-build
  stage: container-build

  rules:
  - if: $CI_COMMIT_BRANCH
  - if: $CI_MERGE_REQUEST_IID
    variables:
      DOCKERBUILD_OUTPUT: "type=image,push=false"
  - if: $CI_OPEN_MERGE_REQUESTS
    when: never

docker:deploy:
  extends: .docker-deploy
  stage: deploy

  rules:
  - if: $CI_COMMIT_BRANCH
  - if: $CI_COMMIT_TAG
