# This files is used to overrides configurations included inside security templates and pipelines

.sast-analyzer:
  stage: sast

.secret-analyzer:
  stage: sast

.ds-analyzer:
  stage: sast

container_scanning:
  stage: compliance

.sysdig-scan:
  stage: compliance
