name: Image Building

on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 1,15 * *"

jobs:
  rebuild-base:
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        params:
        - tag: "1"
          build_args: ""
    with:
      image_path: containers/base
      image_name: base-pipeline
      image_tag: ${{ matrix.params.tag }}
      build_args: ${{ matrix.params.build_args }}
    secrets: inherit

  rebuild-docker:
    needs: rebuild-base
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        params:
        - tag: "1"
          build_args: ""
    with:
      image_path: containers/docker
      image_name: docker-pipeline
      image_tag: ${{ matrix.params.tag }}
      build_args: ${{ matrix.params.build_args }}
    secrets: inherit

  rebuild-go:
    needs: rebuild-base
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        params:
        - tag: "1.25"
          build_args: |
            GO_VERSION=1.25.7
            GO_CHECKSUM=12e6d6a191091ae27dc31f6efc630e3a3b8ba409baf3573d955b196fdf086005
            GO_CHECKSUM_ARM=ba611a53534135a81067240eff9508cd7e256c560edd5d8c2fef54f083c07129
        - tag: "1.26"
          build_args: |
            GO_VERSION=1.26.1
            GO_CHECKSUM=031f088e5d955bab8657ede27ad4e3bc5b7c1ba281f05f245bcc304f327c987a
            GO_CHECKSUM_ARM=a290581cfe4fe28ddd737dde3095f3dbeb7f2e4065cab4eae44dfc53b760c2f7
            GOLANGCI_VERSION=v2.11.2
            LINT_CHECKSUM=852741ea769f4543ab4b6cf86b313cb7173f2e8d2d39f00eb0cd5ef5d4d5eda9
            LINT_CHECKSUM_ARM=c3c83c7ed003e881991af21361c487151abd37969927ed9062cd0b48f3cd1d8d
    with:
      image_path: containers/go
      image_name: golang-pipeline
      image_tag: ${{ matrix.params.tag }}
      build_args: ${{ matrix.params.build_args }}
    secrets: inherit

  rebuild-kubernetes:
    needs: rebuild-base
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        params:
        - tag: "1.32"
          build_args: |
            KUBECTL_VERSION=v1.32.12
            KUBECTL_CHECKSUM=adac5674d19f47ed3f0620bfeb1932d3d5f4557d49f311f6f65b6b75e0721ee1
            KUBECTL_CHECKSUM_ARM=86fa465134c54de6202d89d41eb89504810236cc968e1402a31f3674f66ffdbd
            HELM_VERSION=v3.20.0
            HELM_CHECKSUM=dbb4c8fc8e19d159d1a63dda8db655f9ffa4aac1b9a6b188b34a40957119b286
            HELM_CHECKSUM_ARM=bfb14953295d5324d47ab55f3dfba6da28d46c848978c8fbf412d4271bdc29f1
        - tag: "1.33"
          build_args: |
            KUBECTL_VERSION=v1.33.8
            KUBECTL_CHECKSUM=7f9c3faab7c9f9cc3f318d49eb88efc60eb3b3a7ce9eee5feb39b1280e108a29
            KUBECTL_CHECKSUM_ARM=76e284669f1f6343bd9fe2a011757809c8c01cf51da9f85ee6ef4eb93c8393a8
            HELM_VERSION=v3.20.0
            HELM_CHECKSUM=dbb4c8fc8e19d159d1a63dda8db655f9ffa4aac1b9a6b188b34a40957119b286
            HELM_CHECKSUM_ARM=bfb14953295d5324d47ab55f3dfba6da28d46c848978c8fbf412d4271bdc29f1
        - tag: "1.34"
          build_args: |
            KUBECTL_VERSION=v1.34.4
            KUBECTL_CHECKSUM=d50c359d95e0841eaad08ddc27c7be37cba8fdccfba5c8e2ded65e121ff112db
            KUBECTL_CHECKSUM_ARM=5b982c0644ab1e27780246b9085a5886651b4a7ed86243acbb2bacc1bea01dda
            HELM_VERSION=v3.20.0
            HELM_CHECKSUM=dbb4c8fc8e19d159d1a63dda8db655f9ffa4aac1b9a6b188b34a40957119b286
            HELM_CHECKSUM_ARM=bfb14953295d5324d47ab55f3dfba6da28d46c848978c8fbf412d4271bdc29f1
        - tag: "1.35"
          build_args: ""
    with:
      image_path: containers/kubernetes
      image_name: kubernetes-pipeline
      image_tag: ${{ matrix.params.tag }}
      build_args: ${{ matrix.params.build_args }}
    secrets: inherit

  rebuild-node:
    needs: rebuild-base
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        params:
        - tag: "20"
          build_args: |
            NODE_VERSION=v20.20.0
            NODE_CHECKSUM=4f48b52acf42130844a3a75e94da0e9629009d09e4101b2304895c24f3fbe609
            NODE_CHECKSUM_ARM=752113754a7dddf0622b3740a2b2bec3dbaf1792a18711b55871d76444d8892a
        - tag: "22"
          build_args: |
            NODE_VERSION=v22.22.0
            NODE_CHECKSUM=9aa8e9d2298ab68c600bd6fb86a6c13bce11a4eca1ba9b39d79fa021755d7c37
            NODE_CHECKSUM_ARM=1bf1eb9ee63ffc4e5d324c0b9b62cf4a289f44332dfef9607cea1a0d9596ba6f
        - tag: "24"
          build_args: ""
    with:
      image_path: containers/node
      image_name: node-pipeline
      image_tag: ${{ matrix.params.tag }}
      build_args: ${{ matrix.params.build_args }}
    secrets: inherit

  rebuild-sysdig:
    needs: rebuild-base
    uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        params:
        - tag: "1"
          build_args: ""
    with:
      image_path: containers/sysdig
      image_name: sysdig-pipeline
      image_tag: ${{ matrix.params.tag }}
      build_args: ${{ matrix.params.build_args }}
    secrets: inherit
