name: Go CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

env:
  GO_MAIN_MODULE_PATH: ${{ github.workspace }}
  GOPATH: ${{ github.workspace }}/.cache
  GOLANG_IMAGE_TAG: latest

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GOLANG_IMAGE_TAG }}

      - name: Build
        run: go build ${GO_CLI_OPTS} "${GO_MAIN_MODULE_PATH}"
